### ISSUE TITLE
rickpy.use_dev_packages no longer required.

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/sciunitopt#3]
The Dockerfile build took care of installing these packages in `/opt/conda/lib/python3.5/site-packages`

However the fact these packages are properly installed makes it hard to edit and maintain projects that are in flux.
```
import rickpy
rickpy.use_dev_packages(['rickpy','scidash/sciunit','scidash/neuronunit','neuroml/pyNeuroML'])
```

**Comment by rgerkin** [comment]
Yes, we can get rid of `use_dev_packages` everywhere.
